# Generated by Django 5.2.13 on 2026-04-09 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id_project', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'project',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id_role', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'role',
            },
        ),
        migrations.CreateModel(
            name='TaskPriority',
            fields=[
                ('id_priority', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('level', models.IntegerField()),
            ],
            options={
                'db_table': 'task_priority',
            },
        ),
        migrations.CreateModel(
            name='TaskStatus',
            fields=[
                ('id_status', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'task_status',
            },
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id_user', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('username', models.CharField(max_length=100)),
                ('password_hash', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user_account',
            },
        ),
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id_board', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(db_column='id_project', on_delete=django.db.models.deletion.CASCADE, related_name='boards', to='core.project')),
            ],
            options={
                'db_table': 'board',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id_task', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('board', models.ForeignKey(db_column='id_board', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='core.board')),
                ('priority', models.ForeignKey(blank=True, db_column='id_priority', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='core.taskpriority')),
                ('status', models.ForeignKey(blank=True, db_column='id_status', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='core.taskstatus')),
                ('assigned_to', models.ForeignKey(blank=True, db_column='assigned_to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_assigned', to='core.useraccount')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_created', to='core.useraccount')),
            ],
            options={
                'db_table': 'task',
            },
        ),
        migrations.CreateModel(
            name='TaskComment',
            fields=[
                ('id_comment', models.BigAutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(db_column='id_task', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.task')),
                ('user', models.ForeignKey(blank=True, db_column='id_user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_comments', to='core.useraccount')),
            ],
            options={
                'db_table': 'task_comment',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_created', to='core.useraccount'),
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id_activity', models.BigAutoField(primary_key=True, serialize=False)),
                ('entity_type', models.CharField(blank=True, max_length=50, null=True)),
                ('entity_id', models.IntegerField(blank=True, null=True)),
                ('action', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, db_column='id_user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='core.useraccount')),
            ],
            options={
                'db_table': 'activity_log',
            },
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(db_column='id_project', on_delete=django.db.models.deletion.CASCADE, related_name='members', to='core.project')),
                ('role', models.ForeignKey(blank=True, db_column='id_role', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_members', to='core.role')),
                ('user', models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.CASCADE, related_name='project_memberships', to='core.useraccount')),
            ],
            options={
                'db_table': 'project_member',
                'unique_together': {('user', 'project')},
            },
        ),
    ]
