# Generated by Django 5.2.13 on 2026-04-19 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_githubrepo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemrole',
            name='name',
            field=models.CharField(choices=[('Admin', 'Admin'), ('User', 'User'), ('Stakeholder', 'Stakeholder'), ('Project Manager', 'Project Manager')], max_length=50, unique=True),
        ),
    ]
