# Generated by Django 5.2.13 on 2026-04-21 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_task_multiple_assignments'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='taskassignment',
            name='unique_task_assignment',
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Planeación', 'Planeación'), ('En Progreso', 'En Progreso'), ('Revisión', 'Revisión'), ('Finalizado', 'Finalizado'), ('Retirado', 'Retirado'), ('Cancelado', 'Cancelado')], default='En Progreso', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='taskassignment',
            unique_together={('task', 'assigned_to')},
        ),
    ]
