# Generated by Django to resolve parallel migration branches in core.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_insert_project_roles"),
        ("core", "0018_taskpushmatch_taskwarning_created_in_push"),
    ]

    operations = []
