# Generated by Django 5.2.13 on 2026-04-23 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_project_repo'),
        ('core', '0021_insert_stakeholder_role'),
    ]

    operations = [
    ]
