# Generated by Django 5.2.14 on 2026-05-25 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_rename_role_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='role',
            table='project_role',
        ),
    ]
