# Generated by Django 5.2.14 on 2026-05-25 04:54
# Modified: use SeparateDatabaseAndState because 0041 already renamed the table
# via raw SQL — this migration only updates Django's internal state.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_rename_role_table'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],  # SQL already executed by 0041
            state_operations=[
                migrations.AlterModelTable(
                    name='role',
                    table='project_role',
                ),
            ],
        ),
    ]
