# Generated by Django 5.2.14 on 2026-06-07 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_hackathon_modes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackathonsubmission',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed'), ('batch_pending', 'Batch pending')], default='pending', max_length=20),
        ),
    ]
